language: php

php:
  - 5.4

env:
  global:
    - secure: fzibke3H3NjWA0RVrDf3ZACIOsQkCVmjtXxlBl/fR1GKAjFzeyaG9H4g5PJ4BaQ6vVcr8qUNpAGq2uBNn5f8bJ/Oy2aF4DTnvL5wl5GzHOyEBbBEyp9WPv+O4ZYnk7yT1dmO70mjmAWKjWA6wL1bi5GtimBk6ffrzt7x0glScYQ=

before_script:
  - composer install --prefer-dist
  - gem install capistrano --no-ri --no-rdoc

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
#  - vendor/bin/phpcs --standard=PSR2 src --ignore=vendor
  - php console run:tournament -t 45
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
after_success:
  - "openssl aes-256-cbc -k $DEPLOY_KEY -in deploy/id_rsa_travis_enc -d -a -out deploy/deploy_id_rsa"
  - "chmod 600 deploy/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && cd deploy && cap aws deploy"

notifications:
  email:
    - dardarlt@gmail.com
